"""Regenerate /app/PLUGIN-CATALOG.md — a human-readable catalog of every
NivX Forge decoder plugin currently registered in the engine.

Run this manually or as a pre-deploy step:

    python /app/backend/tools/generate_plugin_catalog.py

The output is a self-updating markdown table analysts and new devs can use
to find "does the engine already know how to decode X?" without reading
source. Every plugin is listed with:
  - id, name, category, description
  - detect() confidence signature (fixed constant if trivially discoverable)
  - example payload from the golden regression suite (if any)

The script is deterministic: same inputs → same output → safe to check in.
"""
from __future__ import annotations
import sys
import inspect
from pathlib import Path
from collections import defaultdict

ROOT = Path("/app")
BACKEND = ROOT / "backend"
sys.path.insert(0, str(BACKEND))

# Force plugin registration by importing the module.
from cyberlab.plugins import decoders as _decoders  # noqa: F401
from cyberlab.plugins.base import _REGISTRY as REGISTRY  # noqa: E402

# Pull golden payloads so we can list one example per plugin category.
from healthbot.checks import _GOLDEN_PAYLOADS  # noqa: E402


def _snippet(plugin) -> str:
    """Try to introspect the detect() function source for a quick hint."""
    try:
        src = inspect.getsource(plugin.detect)
        for line in src.splitlines():
            line = line.strip()
            if line.startswith("return") and any(x in line for x in ("0.", "1.")):
                return line[: 100]
    except Exception:
        pass
    return ""


def main() -> int:
    plugins = list(REGISTRY.values())
    plugins.sort(key=lambda p: (p.category, p.id))

    by_cat: dict[str, list] = defaultdict(list)
    for p in plugins:
        by_cat[p.category].append(p)

    lines: list[str] = []
    lines.append("# NivX Forge — Decoder Plugin Catalog\n")
    lines.append(
        "> Auto-generated by `backend/tools/generate_plugin_catalog.py`. "
        "Do not edit by hand — regenerate to update.\n"
    )
    lines.append(f"**Total plugins**: {len(plugins)}   ·   ")
    lines.append(f"**Categories**: {len(by_cat)}   ·   ")
    lines.append(f"**Golden regression samples**: {len(_GOLDEN_PAYLOADS)}\n")
    lines.append("## Table of contents")
    for cat in sorted(by_cat):
        anchor = cat.lower().replace(" ", "-")
        lines.append(f"- [{cat}](#{anchor}) — {len(by_cat[cat])} plugins")
    lines.append("")

    for cat in sorted(by_cat):
        lines.append(f"## {cat}\n")
        lines.append("| ID | Name | Description | Detect signature |")
        lines.append("| --- | --- | --- | --- |")
        for p in by_cat[cat]:
            desc = (p.description or "").replace("|", "\\|").replace("\n", " ")
            if len(desc) > 180:
                desc = desc[:177] + "…"
            sig = _snippet(p).replace("|", "\\|")
            lines.append(f"| `{p.id}` | {p.name} | {desc} | `{sig}` |")
        lines.append("")

    lines.append("## Golden regression samples\n")
    lines.append(
        "These payloads run through `auto_decode()` + `refine()` on every HealthBot scan. "
        "If any of them fail to decode, `decoder_coverage` turns critical.\n"
    )
    lines.append("| Sample ID | Expected substring | Payload preview |")
    lines.append("| --- | --- | --- |")
    for s in _GOLDEN_PAYLOADS:
        preview = s["input"].replace("|", "\\|").replace("\n", " ")
        if len(preview) > 90:
            preview = preview[:87] + "…"
        lines.append(f"| `{s['id']}` | `{s['must_decode_to_contain']}` | `{preview}` |")
    lines.append("")
    lines.append(
        "*Analysts can add custom samples via Admin → Master → Overview → Regression Suite. "
        "They're stored in Mongo (`healthbot_regression_samples`) and merged into every scan.*"
    )
    lines.append("")
    lines.append(f"---\n*Last regenerated: run `python backend/tools/generate_plugin_catalog.py` any time.*")

    out = ROOT / "PLUGIN-CATALOG.md"
    out.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {out} — {len(plugins)} plugins across {len(by_cat)} categories.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
